=== redbrick/TechWeek/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Root schema.",
  "description": "An explanation about the purpose of this instance.",
  "properties": {
    "location": {
      "type": "string",
      "minLength": 1,
      "title": "Location schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "Dublin City University"
    },
    "start": {
      "type": "integer",
      "multipleOf": 1,
      "maximum": 10000,
      "minimum": 1,
      "exclusiveMaximum": false,
      "exclusiveMinimum": false,
      "title": "Start schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 24
    },
    "end": {
      "type": "integer",
      "multipleOf": 1,
      "maximum": 10000,
      "minimum": 1,
      "exclusiveMaximum": false,
      "exclusiveMinimum": false,
      "title": "End schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 28
    },
    "month": {
      "type": "string",
      "minLength": 1,
      "title": "Month schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "March"
    },
    "year": {
      "type": "integer",
      "multipleOf": 1,
      "maximum": 10000,
      "minimum": 1,
      "exclusiveMaximum": false,
      "exclusiveMinimum": false,
      "title": "Year schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 2017
    },
    "live": {
      "type": "string",
      "minLength": 1,
      "title": "Live schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "2017-03-24T12:00:00"
    },
    "archive": {
      "type": "string",
      "minLength": 1,
      "title": "Archive schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "false"
    },
    "video": {
      "type": "string",
      "minLength": 1,
      "title": "Video schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "days": {
      "type": "array",
      "uniqueItems": false,
      "title": "Days schema.",
      "description": "An explanation about the purpose of this instance.",
      "items": {
        "type": "object",
        "title": "4 schema.",
        "description": "An explanation about the purpose of this instance.",
        "properties": {
          "day": {
            "type": "string",
            "minLength": 1,
            "title": "Day schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": "Friday"
          },
          "description": {
            "type": "string",
            "title": "Description schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": "Lightning Talks"
          },
          "events": {
            "type": "array",
            "uniqueItems": false,
            "title": "Events schema.",
            "description": "An explanation about the purpose of this instance.",
            "items": {
              "type": "object",
              "title": "3 schema.",
              "description": "An explanation about the purpose of this instance.",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1,
                  "title": "Name schema.",
                  "description": "An explanation about the purpose of this instance.",
                  "default": "TBA"
                },
                "by": {
                  "type": "string",
                  "minLength": 1,
                  "title": "By schema.",
                  "description": "An explanation about the purpose of this instance.",
                  "default": "TBA"
                },
                "time": {
                  "type": "string",
                  "minLength": 1,
                  "title": "Time schema.",
                  "description": "An explanation about the purpose of this instance.",
                  "default": "16:00"
                },
                "place": {
                  "type": "object",
                  "title": "Place schema.",
                  "description": "An explanation about the purpose of this instance.",
                  "properties": {
                    "id": {
                      "type": "string",
                      "minLength": 1,
                      "title": "Id schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "default": "The Mezz"
                    },
                    "map": {
                      "type": "string",
                      "minLength": 1,
                      "title": "Map schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "default": "Somewhere in DCU"
                    }
                  },
                  "required": [
                    "id",
                    "map"
                  ]
                },
                "description": {
                  "type": "string",
                  "minLength": 1,
                  "title": "Description schema.",
                  "description": "An explanation about the purpose of this instance.",
                  "default": "TBA"
                }
              },
              "required": [
                "name",
                "by",
                "time",
                "place",
                "description"
              ]
            }
          }
        },
        "required": [
          "day",
          "events"
        ]
      }
    }
  },
  "required": [
    "location",
    "start",
    "end",
    "month",
    "year",
    "days"
  ]
}

=== redbrick/TechWeek/events/2017.json
{
  "location": "Dublin City University",
  "start": 24,
  "end": 28,
  "month": "March",
  "year": 2017,
  "live": "2017-03-24T12:00:00",
  "archive": "false",
  "video": "https://www.youtube.com/embed/videoseries?list=PLPaLJSHTDMFhbDmyUeik6IHXmzVtWQQxu",
  "days": [{
    "day": "Monday",
    "description": "Data",
    "events": [{
      "name": "Opening Event",
      "by": "Redbrick DCU's Computer Networking Society",
      "time": "11:45",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "Opening of TechWeek 2017"
    }, {
      "name": "TBA",
      "by": "TBA",
      "time": "12:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "TBA"
    }, {
      "name": "Lunch",
      "by": "Food",
      "time": "14:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "Lunch Time!"
    }, {
      "name": "TBA",
      "by": "TBA",
      "time": "15:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "TBA"
    }]
  }, {
    "day": "Tuesday",
    "description": "Mobile Development",
    "events": [{
      "name": "TBA",
      "by": "TBA",
      "time": "12:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "TBA"
    }, {
      "name": "Lunch",
      "by": "Food",
      "time": "14:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "Lunch Time!"
    }, {
      "name": "TBA",
      "by": "TBA",
      "time": "15:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "TBA"
    }]
  }, {
    "day": "Wednesday",
    "description": "Networks and IoT",
    "events": [{
      "name": "TBA",
      "by": "TBA",
      "time": "12:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "TBA"
    }, {
      "name": "Lunch",
      "by": "Food",
      "time": "14:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "Lunch Time!"
    }, {
      "name": "TBA",
      "by": "TBA",
      "time": "15:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "TBA"
    }]
  }, {
    "day": "Thursday",
    "description": "STEM",
    "events": [{
      "name": "TBA",
      "by": "TBA",
      "time": "12:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "TBA"
    }, {
      "name": "Lunch",
      "by": "Food",
      "time": "14:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "Lunch Time!"
    }, {
      "name": "TBA",
      "by": "TBA",
      "time": "15:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "TBA"
    }]
  }, {
    "day": "Friday",
    "description": "Lightning Talks",
    "events": [{
      "name": "TBA",
      "by": "TBA",
      "time": "12:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "TBA"
    }, {
      "name": "Lunch",
      "by": "Food",
      "time": "14:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "Lunch Time!"
    }, {
      "name": "TBA",
      "by": "TBA",
      "time": "16:00",
      "place": {
        "id": "The Mezz",
        "map": "Somewhere in DCU"
      },
      "description": "TBA"
    }]
  }]
}
